"""
Tests for np.foo applied to Series, not necessarily ufuncs.
"""

import numpy as np


from pandas import Series


class TestPtp:
        # GH#21614
        N = 1000
        arr = np.random.default_rng(2).standard_normal(N)
        ser = Series(arr)
        assert np.ptp(ser) == np.ptp(arr)


    # it works!
    np.unique(datetime_series)


    # GH#35331

    s = Series(range(5), index=index, dtype=np.int64)

    result = np.argwhere(s > 2).astype(np.int64)
    expected = np.array([[3], [4]], dtype=np.int64)

    tm.assert_numpy_array_equal(result, expected)


@td.skip_if_no("pyarrow")
    # GH#56285
    ser = Series([1, 2, None], dtype="float64[pyarrow]")
    result = np.log(ser)
    expected = np.log(Series([1, 2, None], dtype="float64"))
    tm.assert_series_equal(result, expected)
